In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('qoute_dataset.csv')
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3038 entries, 0 to 3037
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   quote   3038 non-null   object
 1   Author  3038 non-null   object
dtypes: object(2)
memory usage: 47.6+ KB

In [6]:
df.describe()

                                                    quote            Author
count                                                3038              3038
unique                                               3037              1005
top     A woman's heart should be so hidden in God tha...  Cassandra Clare,
freq                                                    2                92

In [7]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [8]:
quotes = quotes.str.lower()

In [9]:
import string

translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [10]:
quotes

0       “the world as we have created it is a process ...
1       “it is our choices harry that show what we tru...
2       “there are only two ways to live your life one...
3       “the person be it gentleman or lady who has no...
4       “imperfection is beauty madness is genius and ...
                              ...
3033         the past beats inside me like a second heart
3034    damn claire warn a guy before you do a facepla...
3035    can you be a girl for a few secondsim always a...
3036    thats what fiction is for its for getting at t...
3037    if we have no peace it is because we have forg...
Name: quote, Length: 3038, dtype: object

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [12]:
vocab_size = 10000

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [13]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [14]:
sequences = tokenizer.texts_to_sequences(quotes)
print(sequences[:5])

[[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461], [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676], [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677], [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12, 2463, 3678], [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54, 682, 3680]]

In [15]:
for i in range(3):
    print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [16]:
for i in range(3):
    print(sequences[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [17]:
X = []
y = []

for seq in sequences:
    for i in range(1, len(seq)):
        input_shape = seq[:i]
        output_seq = seq[i]
        X.append(input_shape)
        y.append(output_seq)

In [18]:
len(X), len(y)

(85271, 85271)

In [19]:
X

[[713],
 [713, 62],
 [713, 62, 29],
 [713, 62, 29, 19],
 [713, 62, 29, 19, 16],
 [713, 62, 29, 19, 16, 946],
 [713, 62, 29, 19, 16, 946, 10],
 [713, 62, 29, 19, 16, 946, 10, 7],
 [713, 62, 29, 19, 16, 946, 10, 7, 5],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752,
  70],
 [947],
 [947, 7],
 [947, 7, 70],
 [947, 7, 70, 871],
 [947, 7, 70, 871, 373],
 [947, 7, 70, 871, 373, 9],
 [947, 7, 70, 871, 373, 9, 433],
 [947, 7, 70, 871, 373, 9, 433, 21],
 [947, 7, 70, 871, 373, 9, 433, 21, 19],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70],
 [1337],
 [1337, 14],
 [1337, 14, 53],
 [1337, 14, 53, 201],
 [1337, 14, 53, 201, 714],
 [1337, 14, 53, 201, 714, 3],
 [1337, 14, 53, 201, 714, 3, 81],
 [1337, 14, 53, 201, 714, 3, 81, 15],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7,
  5],
 [713],
 [713, 116],
 [713, 116, 12],
 [713, 116, 12, 10],
 [713, 116, 12, 10, 2462],
 [713, 116, 12, 10, 2462, 32],
 [713, 116, 12, 10, 2462, 32, 1043],
 [713, 116, 12, 10, 2462, 32, 1043, 30],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12],
 [713,
  116,
  12,
  10,
  2462,
  32,
  1043,
  30,
  82,
  13,
  601,
  11,
  5,
  74,
  1338,
  119,
  12,
  2463],
 [3679],
 [3679, 7],
 [3679, 7, 313],
 [3679, 7, 313, 753],
 [3679, 7, 313, 753, 7],
 [3679, 7, 313, 753, 7, 638],
 [3679, 7, 313, 753, 7, 638, 4],
 [3679, 7, 313, 753, 7, 638, 4, 43],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54, 682],
 [3681],
 [3681, 13],
 [3681, 13, 3],
 [3681, 13, 3, 202],
 [3681, 13, 3, 202, 5],
 [3681, 13, 3, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8],
 [3681, 13, 3, 202, 5, 90, 8, 434],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90, 8],
 [947],
 [947, 7],
 [947, 7, 144],
 [947, 7, 144, 3],
 [947, 7, 144, 3, 12],
 [947, 7, 144, 3, 12, 1340],
 [947, 7, 144, 3, 12, 1340, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2, 14],
 [715],
 [715, 16],
 [715, 16, 13],
 [715, 16, 13, 1341],
 [715, 16, 13, 1341, 191],
 [715, 16, 13, 1341, 191, 51],
 [715, 16, 13, 1341, 191, 51, 415],
 [715, 16, 13, 1341, 191, 51, 415, 2464],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9, 363],
 [1044],
 [1044, 180],
 [1044, 180, 7],
 [1044, 180, 7, 39],
 [1044, 180, 7, 39, 5],
 [1044, 180, 7, 39, 5, 810],
 [1044, 180, 7, 39, 5, 810, 1342],
 [1044, 180, 7, 39, 5, 810, 1342, 2],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11, 639],
 [1044],
 [1044, 111],
 [1044, 111, 104],
 [1044, 111, 104, 1045],
 [1044, 111, 104, 1045, 7],
 [1044, 111, 104, 1045, 7, 39],
 [1044, 111, 104, 1045, 7, 39, 2],
 [1044, 111, 104, 1045, 7, 39, 2, 50],
 [2465],
 [2465, 36],
 [2465, 36, 7],
 [2465, 36, 7, 21],
 [2465, 36, 7, 21, 2],
 [2465, 36, 7, 21, 2, 65],
 [2465, 36, 7, 21, 2, 65, 10],
 [2465, 36, 7, 21, 2, 65, 10, 47],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43, 5],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15,
  161],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,

In [20]:
y

[62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461,
 7,
 70,
 871,
 373,
 9,
 433,
 21,
 19,
 465,
 14,
 294,
 52,
 54,
 70,
 3676,
 14,
 53,
 201,
 714,
 3,
 81,
 15,
 36,
 37,
 7,
 29,
 329,
 93,
 7,
 5,
 1157,
 1,
 101,
 7,
 29,
 329,
 126,
 7,
 5,
 3677,
 116,
 12,
 10,
 2462,
 32,
 1043,
 30,
 82,
 13,
 601,
 11,
 5,
 74,
 1338,
 119,
 12,
 2463,
 3678,
 7,
 313,
 753,
 7,
 638,
 4,
 43,
 144,
 3,
 12,
 682,
 1339,
 54,
 682,
 3680,
 13,
 3,
 202,
 5,
 90,
 8,
 434,
 279,
 202,
 5,
 90,
 8,
 3682,
 7,
 144,
 3,
 12,
 1340,
 17,
 21,
 2,
 14,
 54,
 3,
 12,
 175,
 17,
 21,
 2,
 14,
 3683,
 16,
 13,
 1341,
 191,
 51,
 415,
 2464,
 714,
 9,
 363,
 3684,
 180,
 7,
 39,
 5,
 810,
 1342,
 2,
 46,
 50,
 59,
 322,
 10,
 7,
 168,
 43,
 11,
 639,
 3685,
 111,
 104,
 1045,
 7,
 39,
 2,
 50,
 3686,
 36,
 7,
 21,
 2,
 65,
 10,
 47,
 181,
 21,
 96,
 130,
 3,
 754,
 58,
 123,
 43,
 5,
 1939,
 174,
 18,
 1,
 74,
 208,
 7,
 2,
 94,
 3,
 466,
 59,
 96,
 130,
 3,
 754,
 10,
 58,
 516,
 28,
 12,
 15,
 212,
 948,
 517,
 39,
 10,
 811,
 18,
 51,
 158,
 89,
 132,
 89,
 79,
 1,
 234,
 9,
 271,
 22,
 2,
 146,
 126,
 272,
 15,
 161,
 159,
 212,
 49,
 102,
 79,
 8,
 48,
 389,
 158,
 2466,
 65,
 1,
 159,
 212,
 11,
 1,
 62,
 29,
 17,
 1343,
 167,
 948,
 132,
 4,
 79,
 85,
 4,
 812,
 6,
 273,
 3,
 118,
 10,
 117,
 8,
 48,
 482,
 416,
 105,
 23,
 8,
 48,
 14,
 130,
 3,
 390,
 15,
 92,
 18,
 2,
 140,
 133,
 58,
 55,
 20,
 2,
 133,
 58,
 237,
 46,
 113,
 15,
 2467,
 237,
 46,
 113,
 9,
 417,
 30,
 213,
 2,
 252,
 4,
 9,
 418,
 17,
 126,
 51,
 55,
 2,
 683,
 186,
 182,
 266,
 96,
 1046,
 683,
 44,
 126,
 176,
 260,
 343,
 42,
 4,
 69,
 69,
 69,
 127,
 11,
 100,
 55,
 20,
 2,
 49,
 86,
 30,
 28,
 2468,
 45,
 176,
 15,
 304,
 419,
 176,
 15,
 1570,
 58,
 4,
 117,
 1571,
 176,
 813,
 55,
 872,
 5,
 192,
 91,
 4,
 205,
 45,
 105,
 3,
 289,
 3687,
 344,
 5,
 151,
 640,
 8,
 873,
 3,
 314,
 58,
 3,
 70,
 755,
 18,
 51,
 29,
 105,
 3,
 314,
 58,
 3,
 70,
 3688,
 2,
 140,
 949,
 10,
 3,
 5,
 950,
 467,
 261,
 2,
 49,
 224,
 10,
 1940,
 134,
 13,
 12,
 77,
 178,
 77,
 262,
 32,
 77,
 53,
 76,
 175,
 183,
 76,
 134,
 24,
 170,
 18,
 20,
 76,
 225,
 2,
 147,
 21,
 171,
 602,
 574,
 13,
 2469,
 435,
 404,
 4,
 1,
 201,
 8,
 2,
 134,
 46,
 12,
 345,
 267,
 18,
 20,
 76,
 25,
 65,
 2,
 295,
 951,
 2,
 3,
 64,
 1049,
 4,
 952,
 3,
 128,
 187,
 4,
 354,
 391,
 343,
 953,
 77,
 4,
 133,
 77,
 1,
 117,
 2,
 25,
 76,
 134,
 13,
 12,
 293,
 66,
 2,
 87,
 452,
 8,
 1,
 111,
 18,
 76,
 28,
 133,
 2,
 5,
 208,
 8,
 77,
 9,
 76,
 274,
 2,
 25,
 2470,
 92,
 45,
 49,
 290,
 77,
 49,
 155,
 77,
 49,
 1941,
 4,
 49,
 453,
 52,
 54,
 76,
 25,
 133,
 289,
 27,
 76,
 213,
 2,
 193,
 102,
 77,
 50,
 27,
 76,
 213,
 2,
 436,
 4,
 575,
 77,
 27,
 574,
 13,
 3689,
 39,
 874,
 10,
 1572,
 58,
 1,
 814,
 1942,
 603,
 7,
 5,
 604,
 1943,
 11,
 3690,
 134,
 13,
 16,
 330,
 135,
 6,
 2471,
 3,
 79,
 18,
 6,
 64,
 6,
 16,
 1944,
 58,
 135,
 6,
 756,
 3,
 1945,
 815,
 8,
 24,
 7,
 13,
 273,
 43,
 816,
 1,
 815,
 8,
 495,
 7,
 13,
 1946,
 43,
 816,
 1,
 815,
 8,
 605,
 7,
 13,
 2472,
 43,
 816,
 4,
 1,
 815,
 8,
 36,
 7,
 13,
 214,
 43,
 3691,
 7,
 13,
 5,
 875,
 8,
 24,
 18,
 5,
 875,
 8,
 437,
 9,
 213,
 757,
 3692,
 212,
 74,
 114,
 4,
 5,
 2474,
 876,
 56,
 7,
 1,
 1573,
 3693,
 7,
 21,
 323,
 3,
 73,
 232,
 19,
 14,
 354,
 101,
 3694,
 24,
 2,
 104,
 364,
 59,
 32,
 27,
 32,
 68,
 135,
 6,
 24,
 2,
 576,
 104,
 817,
 32,
 877,
 6,
 24,
 2,
 11,
 56,
 78,
 55,
 6,
 31,
 13,
 50,
 148,
 101,
 78,
 8,
 392,
 18,
 56,
 11,
 120,
 40,
 7,
 47,
 6,
 32,
 2,
 45,
 1344,
 9,
 15,
 315,
 244,
 26,
 758,
 7,
 26,
 315,
 45,
 1344,
 9,
 27,
 6,
 228,
 684,
 15,
 222,
 3695,
 87,
 641,
 2,
 14,
 759,
 2,
 239,
 1948,
 1345,
 8,
 3697,
 2,
 716,
 41,
 2,
 16,
 47,
 67,
 3,
 24,
 3698,
 30,
 577,
 954,
 11,
 1574,
 25,
 65,
 2,
 5,
 1575,
 119,
 389,
 64,
 9,
 954,
 11,
 5,
 1949,
 25,
 65,
 2,
 5,
 3699,
 7,
 11,
 1,
 717,
 8,
 1,
 1576,
 4,
 10,
 134,
 12,
 604,
 68,
 67,
 3,
 67,
 3,
 133,
 5,
 346,
 32,
 1577,
 1576,
 5,
 468,
 3701,
 2,
 14,
 2,
 9,
 7,
 1950,
 54,
 161,
 40,
 7,
 47,
 37,
 393,
 30,
 7,
 2476,
 54,
 2477,
 2,
 57,
 15,
 347,
 3,
 12,
 578,
 124,
 48,
 685,
 686,
 20,
 2,
 57,
 48,
 3,
 12,
 52,
 578,
 124,
 48,
 52,
 685,
 3703,
 7,
 374,
 3,
 81,
 104,
 1578,
 44,
 83,
 469,
 2,
 81,
 45,
 2478,
 9,
 2,
 253,
 29,
 167,
 13,
 16,
 420,
 44,
 23,
 11,
 120,
 818,
 2,
 683,
 63,
 3704,
 28,
 94,
 2,
 68,
 5,
 3,
 1579,
 496,
 28,
 94,
 2,
 3706,
 74,
 91,
 66,
 305,
 27,
 10,
 1158,
 2,
 2,
 131,
 47,
 3708,
 52,
 9,
 2,
 124,
 1,
 52,
 61,
 2,
 28,
 50,
 1,
 52,
 9,
 2,
 203,
 1,
 52,
 642,
 237,
 3709,
 483,
 10,
 7,
 955,
 217,
 15,
 304,
 373,
 18,
 172,
 42,
 275,
 125,
 9,
 266,
 9,
 10,
 7,
 13,
 3711,
 174,
 7,
 235,
 7,
 130,
 3,
 290,
 2,
 2,
 51,
 206,
 3,
 113,
 1,
 234,
 331,
 405,
 3712,
 23,
 8,
 73,
 25,
 31,
 151,
 61,
 18,
 19,
 25,
 31,
 296,
 61,
 22,
 151,
 1951,
 1,
 2480,
 165,
 214,
 7,
 18,
 1,
 394,
 151,
 2481,
 2,
 164,
 7,
 24,
 18,
 5,
 139,
 1346,
 147,
 4,
 86,
 182,
 3714,
 124,
 3,
 50,
 88,
 13,
 3715,
 518,
 25,
 50,
 1,
 332,
 7,
 3,
 3717,
 16,
 69,
 1581,
 9,
 1582,
 28,
 12,
 5,
 194,
 8,
 2483,
 7,
 46,
 85,
 606,
 3,
 12,
 ...]

In [21]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [22]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [23]:
X_padded[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 713], dtype=int32)

In [24]:
X[0]

[713]

In [25]:
y = np.array(y)

In [26]:
y.shape

(85271,)

In [27]:
X_padded.shape

(85271, 745)

In [28]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes = vocab_size)

In [29]:
y_one_hot.shape

(85271, 10000)

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, SimpleRNN, GRU

In [31]:
embeddings_dim = 50
rnn_units = 128

In [32]:
rnn_model = Sequential()
rnn_model.add(Embedding(input_dim=vocab_size, output_dim=embeddings_dim, input_length=max_len))
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [33]:
rnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [34]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
lstm_model = Sequential()
lstm_model.add(Embedding(input_dim=vocab_size, output_dim=embeddings_dim, input_length=max_len))
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [36]:
lstm_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [37]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
gru_model = Sequential()
gru_model.add(Embedding(input_dim=vocab_size, output_dim=embeddings_dim, input_length=max_len))
gru_model.add(GRU(units=rnn_units))
gru_model.add(Dense(units=vocab_size, activation='softmax'))

In [39]:
gru_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [40]:
gru_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
# rnn_model.fit(X_padded, y_one_hot, epochs=10, batch_size=128, validation_split=0.2)
# lstm_model.fit(X_padded, y_one_hot, epochs=100, batch_size=128, validation_split=0.2)
gru_model.fit(X_padded, y_one_hot, epochs=100, batch_size=128, validation_split=0.2)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 57ms/step - accuracy: 0.0406 - loss: 6.8159 - val_accuracy: 0.0567 - val_loss: 6.6199
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 28s 52ms/step - accuracy: 0.0740 - loss: 6.1294 - val_accuracy: 0.0809 - val_loss: 6.4612
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 28s 53ms/step - accuracy: 0.0991 - loss: 5.7952 - val_accuracy: 0.0966 - val_loss: 6.4100
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 28s 53ms/step - accuracy: 0.1167 - loss: 5.5125 - val_accuracy: 0.1074 - val_loss: 6.4078
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1322 - loss: 5.2567 - val_accuracy: 0.1100 - val_loss: 6.4333
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.1440 - loss: 5.0258 - val_accuracy: 0.1117 - val_loss: 6.4882
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.1563 - loss: 4.8102 - val_accuracy: 0.1135 - val_loss: 6.5235
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 34s 64ms/step - accuracy: 0.1700 - loss: 4.6044 - val_accuracy: 0.1128 - val_loss: 6.5882
Epoch 9/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1852 - loss: 4.4072 - val_accuracy: 0.1147 - val_loss: 6.6580
Epoch 10/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.2048 - loss: 4.2176 - val_accuracy: 0.1137 - val_loss: 6.7322
Epoch 11/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2287 - loss: 4.0372 - val_accuracy: 0.1142 - val_loss: 6.7927
Epoch 12/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2523 - loss: 3.8677 - val_accuracy: 0.1109 - val_loss: 6.8684
Epoch 13/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2748 - loss: 3.7098 - val_accuracy: 0.1098 - val_loss: 6.9321
Epoch 14/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2976 - loss: 3.5642 - val_accuracy: 0.1071 - val_loss: 7.0045
Epoch 15/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.3192 - loss: 3.4283 - val_accuracy: 0.1094 - val_loss: 7.0687
Epoch 16/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.3387 - loss: 3.3046 - val_accuracy: 0.1073 - val_loss: 7.1429
Epoch 17/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.3551 - loss: 3.1906 - val_accuracy: 0.1058 - val_loss: 7.1938
Epoch 18/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.3732 - loss: 3.0840 - val_accuracy: 0.1024 - val_loss: 7.2244
Epoch 19/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.3897 - loss: 2.9836 - val_accuracy: 0.1046 - val_loss: 7.3322
Epoch 20/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.4048 - loss: 2.8906 - val_accuracy: 0.1033 - val_loss: 7.4044
Epoch 21/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.4188 - loss: 2.8060 - val_accuracy: 0.1015 - val_loss: 7.4611
Epoch 22/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.4334 - loss: 2.7216 - val_accuracy: 0.1011 - val_loss: 7.4790
Epoch 23/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.4460 - loss: 2.6448 - val_accuracy: 0.1001 - val_loss: 7.5414
Epoch 24/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4583 - loss: 2.5731 - val_accuracy: 0.0987 - val_loss: 7.6399
Epoch 25/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.4709 - loss: 2.5025 - val_accuracy: 0.1000 - val_loss: 7.7034
Epoch 26/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.4838 - loss: 2.4373 - val_accuracy: 0.0989 - val_loss: 7.7662
Epoch 27/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.4953 - loss: 2.3767 - val_accuracy: 0.0981 - val_loss: 7.8289
Epoch 28/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.5055 - loss: 2.3174 - val_accuracy: 0.0972 - val_loss: 7.8930
Epoch 29/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5160 - loss: 2.2628 - val_accuracy: 0.0940 - val_loss: 7.9422
Epoch 30/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5261 - loss: 2.2107 - val_accuracy: 0.0936 - val_loss: 8.0093
Epoch 31/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.5353 - loss: 2.1619 - val_accuracy: 0.0922 - val_loss: 8.0647
Epoch 32/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5438 - loss: 2.1136 - val_accuracy: 0.0942 - val_loss: 8.0973
Epoch 33/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5534 - loss: 2.0674 - val_accuracy: 0.0939 - val_loss: 8.1884
Epoch 34/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5604 - loss: 2.0245 - val_accuracy: 0.0916 - val_loss: 8.2605
Epoch 35/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5690 - loss: 1.9832 - val_accuracy: 0.0903 - val_loss: 8.3143
Epoch 36/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5759 - loss: 1.9438 - val_accuracy: 0.0900 - val_loss: 8.3678
Epoch 37/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5830 - loss: 1.9082 - val_accuracy: 0.0872 - val_loss: 8.4313
Epoch 38/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5907 - loss: 1.8698 - val_accuracy: 0.0891 - val_loss: 8.4846
Epoch 39/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5961 - loss: 1.8354 - val_accuracy: 0.0882 - val_loss: 8.5520
Epoch 40/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6044 - loss: 1.8023 - val_accuracy: 0.0875 - val_loss: 8.6075
Epoch 41/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.6098 - loss: 1.7693 - val_accuracy: 0.0875 - val_loss: 8.6800
Epoch 42/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6165 - loss: 1.7396 - val_accuracy: 0.0854 - val_loss: 8.7287
Epoch 43/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6232 - loss: 1.7074 - val_accuracy: 0.0858 - val_loss: 8.7983
Epoch 44/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6289 - loss: 1.6791 - val_accuracy: 0.0855 - val_loss: 8.8500
Epoch 45/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6339 - loss: 1.6547 - val_accuracy: 0.0826 - val_loss: 8.9223
Epoch 46/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.6394 - loss: 1.6266 - val_accuracy: 0.0833 - val_loss: 8.9768
Epoch 47/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6457 - loss: 1.5991 - val_accuracy: 0.0813 - val_loss: 9.0221
Epoch 48/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 57ms/step - accuracy: 0.6488 - loss: 1.5773 - val_accuracy: 0.0805 - val_loss: 9.0808
Epoch 49/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6547 - loss: 1.5524 - val_accuracy: 0.0832 - val_loss: 9.1530
Epoch 50/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.6596 - loss: 1.5301 - val_accuracy: 0.0838 - val_loss: 9.2042
Epoch 51/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6644 - loss: 1.5071 - val_accuracy: 0.0810 - val_loss: 9.2262
Epoch 52/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6691 - loss: 1.4883 - val_accuracy: 0.0831 - val_loss: 9.3000
Epoch 53/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6719 - loss: 1.4617 - val_accuracy: 0.0832 - val_loss: 9.3751
Epoch 54/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6775 - loss: 1.4436 - val_accuracy: 0.0809 - val_loss: 9.4151
Epoch 55/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6807 - loss: 1.4240 - val_accuracy: 0.0803 - val_loss: 9.4869
Epoch 56/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6850 - loss: 1.4046 - val_accuracy: 0.0798 - val_loss: 9.5345
Epoch 57/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6897 - loss: 1.3862 - val_accuracy: 0.0794 - val_loss: 9.5852
Epoch 58/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6921 - loss: 1.3696 - val_accuracy: 0.0795 - val_loss: 9.6453
Epoch 59/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6976 - loss: 1.3511 - val_accuracy: 0.0816 - val_loss: 9.7123
Epoch 60/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7001 - loss: 1.3341 - val_accuracy: 0.0787 - val_loss: 9.7596
Epoch 61/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.7030 - loss: 1.3199 - val_accuracy: 0.0794 - val_loss: 9.8097
Epoch 62/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7060 - loss: 1.3034 - val_accuracy: 0.0795 - val_loss: 9.8584
Epoch 63/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7106 - loss: 1.2833 - val_accuracy: 0.0794 - val_loss: 9.9129
Epoch 64/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7129 - loss: 1.2720 - val_accuracy: 0.0786 - val_loss: 9.9436
Epoch 65/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7150 - loss: 1.2607 - val_accuracy: 0.0787 - val_loss: 10.0166
Epoch 66/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7184 - loss: 1.2467 - val_accuracy: 0.0758 - val_loss: 10.0769
Epoch 67/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7246 - loss: 1.2263 - val_accuracy: 0.0759 - val_loss: 10.1157
Epoch 68/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 43s 60ms/step - accuracy: 0.7248 - loss: 1.2156 - val_accuracy: 0.0776 - val_loss: 10.1705
Epoch 69/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7257 - loss: 1.2109 - val_accuracy: 0.0767 - val_loss: 10.2109
Epoch 70/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.7294 - loss: 1.1965 - val_accuracy: 0.0753 - val_loss: 10.2710
Epoch 71/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 39s 57ms/step - accuracy: 0.7313 - loss: 1.1858 - val_accuracy: 0.0762 - val_loss: 10.3226
Epoch 72/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7342 - loss: 1.1704 - val_accuracy: 0.0774 - val_loss: 10.3620
Epoch 73/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7371 - loss: 1.1604 - val_accuracy: 0.0780 - val_loss: 10.4140
Epoch 74/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 58ms/step - accuracy: 0.7407 - loss: 1.1420 - val_accuracy: 0.0768 - val_loss: 10.4562
Epoch 75/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7424 - loss: 1.1359 - val_accuracy: 0.0765 - val_loss: 10.5078
Epoch 76/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7437 - loss: 1.1277 - val_accuracy: 0.0744 - val_loss: 10.5803
Epoch 77/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7456 - loss: 1.1183 - val_accuracy: 0.0756 - val_loss: 10.6087
Epoch 78/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.7499 - loss: 1.1065 - val_accuracy: 0.0741 - val_loss: 10.6605
Epoch 79/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 39s 56ms/step - accuracy: 0.7535 - loss: 1.0901 - val_accuracy: 0.0746 - val_loss: 10.7203
Epoch 80/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7527 - loss: 1.0835 - val_accuracy: 0.0759 - val_loss: 10.7367
Epoch 81/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7541 - loss: 1.0773 - val_accuracy: 0.0743 - val_loss: 10.7883
Epoch 82/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7578 - loss: 1.0672 - val_accuracy: 0.0737 - val_loss: 10.8355
Epoch 83/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7614 - loss: 1.0506 - val_accuracy: 0.0741 - val_loss: 10.8912
Epoch 84/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7624 - loss: 1.0455 - val_accuracy: 0.0744 - val_loss: 10.9377
Epoch 85/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7646 - loss: 1.0405 - val_accuracy: 0.0751 - val_loss: 10.9981
Epoch 86/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7630 - loss: 1.0377 - val_accuracy: 0.0712 - val_loss: 11.0090
Epoch 87/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7601 - loss: 1.0418 - val_accuracy: 0.0742 - val_loss: 11.0587
Epoch 88/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.7692 - loss: 1.0130 - val_accuracy: 0.0744 - val_loss: 11.1248
Epoch 89/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7724 - loss: 0.9993 - val_accuracy: 0.0729 - val_loss: 11.1631
Epoch 90/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7721 - loss: 0.9964 - val_accuracy: 0.0721 - val_loss: 11.2068
Epoch 91/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7727 - loss: 0.9931 - val_accuracy: 0.0707 - val_loss: 11.2631
Epoch 92/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7666 - loss: 1.0092 - val_accuracy: 0.0725 - val_loss: 11.2932
Epoch 93/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7763 - loss: 0.9761 - val_accuracy: 0.0726 - val_loss: 11.3358
Epoch 94/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.7786 - loss: 0.9726 - val_accuracy: 0.0720 - val_loss: 11.3746
Epoch 95/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7809 - loss: 0.9589 - val_accuracy: 0.0712 - val_loss: 11.4132
Epoch 96/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7813 - loss: 0.9563 - val_accuracy: 0.0722 - val_loss: 11.4495
Epoch 97/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7768 - loss: 0.9695 - val_accuracy: 0.0719 - val_loss: 11.4899
Epoch 98/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.7846 - loss: 0.9408 - val_accuracy: 0.0730 - val_loss: 11.5303
Epoch 99/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7871 - loss: 0.9254 - val_accuracy: 0.0713 - val_loss: 11.5792
Epoch 100/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.7853 - loss: 0.9361 - val_accuracy: 0.0704 - val_loss: 11.6474

In [42]:
# lstm_model.save('lstm_model.h5')
gru_model.save('gru_model.h5')
# rnn_model.save('rnn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [43]:
index_to_word = {}

for word, index in word_index.items():
  index_to_word[index] = word

In [44]:
index_to_word

{1: 'the',
 2: 'you',
 3: 'to',
 4: 'and',
 5: 'a',
 6: 'i',
 7: 'is',
 8: 'of',
 9: 'that',
 10: 'it',
 11: 'in',
 12: 'be',
 13: 'not',
 14: 'are',
 15: 'your',
 16: 'have',
 17: 'for',
 18: 'but',
 19: 'we',
 20: 'if',
 21: 'what',
 22: 'with',
 23: 'all',
 24: 'love',
 25: 'can',
 26: 'my',
 27: 'when',
 28: 'will',
 29: 'as',
 30: 'who',
 31: 'do',
 32: 'or',
 33: 'me',
 34: 'he',
 35: 'they',
 36: 'life',
 37: 'one',
 38: 'was',
 39: 'like',
 40: 'there',
 41: 'people',
 42: 'on',
 43: 'its',
 44: 'at',
 45: 'so',
 46: 'never',
 47: 'no',
 48: 'them',
 49: 'dont',
 50: 'know',
 51: 'just',
 52: 'more',
 53: 'only',
 54: 'than',
 55: 'because',
 56: 'this',
 57: 'want',
 58: 'up',
 59: 'how',
 60: 'his',
 61: 'things',
 62: 'world',
 63: 'by',
 64: 'think',
 65: 'make',
 66: 'about',
 67: 'time',
 68: 'from',
 69: 'always',
 70: 'our',
 71: 'an',
 72: 'out',
 73: 'us',
 74: 'good',
 75: 'said',
 76: 'she',
 77: 'her',
 78: 'way',
 79: 'go',
 80: 'am',
 81: 'live',
 82: 'has',
 83: 'something',
 84: 'see',
 85: 'too',
 86: 'then',
 87: 'every',
 88: 'were',
 89: 'some',
 90: 'man',
 91: 'thing',
 92: 'heart',
 93: 'nothing',
 94: 'get',
 95: 'him',
 96: 'youre',
 97: 'would',
 98: 'those',
 99: 'their',
 100: 'yourself',
 101: 'other',
 102: 'let',
 103: 'into',
 104: 'without',
 105: 'much',
 106: 'im',
 107: 'could',
 108: 'had',
 109: 'someone',
 110: 'ever',
 111: 'day',
 112: 'even',
 113: 'find',
 114: 'books',
 115: 'right',
 116: 'person',
 117: 'most',
 118: 'say',
 119: 'must',
 120: 'which',
 121: 'been',
 122: 'own',
 123: 'sometimes',
 124: 'read',
 125: 'should',
 126: 'everything',
 127: 'believe',
 128: 'being',
 129: 'really',
 130: 'going',
 131: 'feel',
 132: 'come',
 133: 'give',
 134: 'may',
 135: 'where',
 136: 'book',
 137: 'thats',
 138: 'tell',
 139: 'little',
 140: 'cant',
 141: 'back',
 142: 'words',
 143: 'over',
 144: 'better',
 145: 'cannot',
 146: 'through',
 147: 'now',
 148: 'any',
 149: 'enough',
 150: 'does',
 151: 'great',
 152: 'god',
 153: 'look',
 154: 'anything',
 155: 'change',
 156: 'another',
 157: 'many',
 158: 'remember',
 159: 'best',
 160: 'down',
 161: 'true',
 162: 'still',
 163: 'did',
 164: 'need',
 165: 'mind',
 166: 'soul',
 167: 'well',
 168: 'until',
 169: 'each',
 170: 'again',
 171: 'else',
 172: 'why',
 173: 'long',
 174: 'truth',
 175: 'loved',
 176: 'keep',
 177: 'very',
 178: 'first',
 179: 'moment',
 180: 'woman',
 181: 'matter',
 182: 'doesnt',
 183: 'before',
 184: 'men',
 185: 'others',
 186: 'once',
 187: 'human',
 188: 'fear',
 189: 'end',
 190: 'around',
 191: 'ive',
 192: 'beautiful',
 193: 'happy',
 194: 'kind',
 195: 'don’t',
 196: 'die',
 197: 'girl',
 198: 'happiness',
 199: 'made',
 200: 'take',
 201: 'two',
 202: 'become',
 203: 'learn',
 204: 'myself',
 205: 'theres',
 206: 'got',
 207: 'hope',
 208: 'part',
 209: 'same',
 210: 'alone',
 211: 'pain',
 212: 'friends',
 213: 'makes',
 214: 'death',
 215: 'real',
 216: 'friend',
 217: 'inside',
 218: 'thought',
 219: 'after',
 220: 'years',
 221: 'here',
 222: 'eyes',
 223: 'wrong',
 224: 'understand',
 225: 'loves',
 226: 'lives',
 227: 'reading',
 228: 'fall',
 229: 'new',
 230: 'light',
 231: 'forever',
 232: 'while',
 233: 'dream',
 234: 'ones',
 235: 'everyone',
 236: 'living',
 237: 'youll',
 238: 'bad',
 239: 'lose',
 240: 'away',
 241: 'forget',
 242: 'shall',
 243: 'hard',
 244: 'upon',
 245: 'between',
 246: 'face',
 247: 'stop',
 248: 'write',
 249: 'dreams',
 250: 'off',
 251: 'future',
 252: 'whole',
 253: 'might',
 254: 'maybe',
 255: 'ourselves',
 256: 'hell',
 257: 'looking',
 258: 'stars',
 259: 'wanted',
 260: 'trying',
 261: 'old',
 262: 'last',
 263: 'isnt',
 264: 'courage',
 265: 'try',
 266: 'mean',
 267: 'together',
 268: 'doing',
 269: 'place',
 270: 'less',
 271: 'stay',
 272: 'theyre',
 273: 'hate',
 274: 'knows',
 275: 'earth',
 276: 'put',
 277: 'felt',
 278: 'times',
 279: 'rather',
 280: 'often',
 281: 'work',
 282: 'night',
 283: 'trust',
 284: 'grow',
 285: 'walk',
 286: 'says',
 287: 'saying',
 288: 'anyone',
 289: 'smile',
 290: 'hurt',
 291: 'story',
 292: 'listen',
 293: 'thinking',
 294: 'far',
 295: 'laugh',
 296: 'small',
 297: 'having',
 298: 'reality',
 299: 'means',
 300: 'women',
 301: 'sad',
 302: 'leave',
 303: 'these',
 304: 'head',
 305: 'music',
 306: 'i’m',
 307: 'youve',
 308: 'it’s',
 309: 'important',
 310: 'somebody',
 311: 'against',
 312: 'feeling',
 313: 'beauty',
 314: 'stand',
 315: 'hand',
 316: 'done',
 317: 'reason',
 318: 'universe',
 319: 'didnt',
 320: 'fire',
 321: 'told',
 322: 'strong',
 323: 'happens',
 324: 'sure',
 325: 'talk',
 326: 'word',
 327: 'himself',
 328: 'full',
 329: 'though',
 330: 'gone',
 331: 'worth',
 332: 'point',
 333: 'door',
 334: 'broken',
 335: 'dark',
 336: 'sit',
 337: 'wish',
 338: 'happen',
 339: 'you’re',
 340: 'least',
 341: 'past',
 342: 'comes',
 343: 'hold',
 344: 'takes',
 345: 'perfect',
 346: 'stupid',
 347: 'children',
 348: 'start',
 349: 'experience',
 350: 'power',
 351: 'yet',
 352: 'asked',
 353: 'realize',
 354: 'making',
 355: 'behind',
 356: 'left',
 357: 'wants',
 358: 'choose',
 359: 'lot',
 360: 'whatever',
 361: 'lost',
 362: 'looked',
 363: 'wont',
 364: 'knowing',
 365: 'few',
 366: 'lie',
 367: 'different',
 368: 'hear',
 369: 'afraid',
 370: 'jace',
 371: 'ask',
 372: 'home',
 373: 'harry',
 374: 'impossible',
 375: 'lies',
 376: 'open',
 377: 'easy',
 378: 'already',
 379: 'three',
 380: 'exist',
 381: 'such',
 382: 'possible',
 383: 'use',
 384: 'thoughts',
 385: 'within',
 386: 'days',
 387: '—',
 388: 'themselves',
 389: 'also',
 390: 'break',
 391: 'mistakes',
 392: 'loving',
 393: 'alive',
 394: 'next',
 395: 'happened',
 396: 'wait',
 397: 'side',
 398: 'both',
 399: 'ill',
 400: 'secret',
 401: 'deep',
 402: 'sleep',
 403: 'silence',
 404: 'either',
 405: 'suffering',
 406: 'tomorrow',
 407: 'call',
 408: 'strength',
 409: 'help',
 410: 'meant',
 411: 'knew',
 412: 'speak',
 413: 'itself',
 414: 'seen',
 415: 'found',
 416: 'pretty',
 417: 'half',
 418: 'goes',
 419: 'high',
 420: 'lived',
 421: 'darkness',
 422: 'yours',
 423: 'choice',
 424: 'forgive',
 425: 'respect',
 426: 'young',
 427: 'simple',
 428: 'close',
 429: 'kill',
 430: 'beginning',
 431: 'whats',
 432: 'perhaps',
 433: 'show',
 434: 'success',
 435: 'arent',
 436: 'mad',
 437: 'friendship',
 438: 'thousand',
 439: 'crazy',
 440: 'house',
 441: 'nobody',
 442: 'history',
 443: 'able',
 444: 'set',
 445: 'meet',
 446: 'hands',
 447: 'rest',
 448: 'answer',
 449: 'id',
 450: 'voice',
 451: 'dare',
 452: 'second',
 453: 'expect',
 454: 'war',
 455: 'free',
 456: 'room',
 457: 'seems',
 458: 'somewhere',
 459: 'care',
 460: 'couldnt',
 461: 'fight',
 462: 'known',
 463: 'lonely',
 464: 'family',
 465: 'truly',
 466: 'decide',
 467: 'year',
 468: 'black',
 469: 'unless',
 470: 'begin',
 471: 'turn',
 472: 'sun',
 473: 'body',
 474: 'today',
 475: 'enjoy',
 476: 'child',
 477: 'fact',
 478: 'worse',
 479: 'yes',
 480: 'freedom',
 481: 'mother',
 482: 'actually',
 483: 'course',
 484: 'born',
 485: 'seem',
 486: 'difference',
 487: 'dead',
 488: 'taste',
 489: 'everybody',
 490: 'peace',
 491: 'took',
 492: '–',
 493: 'stories',
 494: 'loneliness',
 495: 'art',
 496: 'imagination',
 497: 'wise',
 498: 'big',
 499: 'question',
 500: 'boy',
 501: 'learned',
 502: 'single',
 503: 'completely',
 504: 'water',
 505: 'knowledge',
 506: 'gives',
 507: 'hes',
 508: 'wisdom',
 509: 'desire',
 510: 'carry',
 511: 'gets',
 512: 'sea',
 513: 'waste',
 514: 'bear',
 515: 'father',
 516: 'girls',
 517: 'act',
 518: 'fool',
 519: 'persons',
 520: 'control',
 521: 'finally',
 522: 'apart',
 523: 'special',
 524: 'quite',
 525: 'stronger',
 526: 'imagine',
 527: 'name',
 528: 'hurts',
 529: 'minds',
 530: 'under',
 531: 'teach',
 532: 'school',
 533: 'nice',
 534: 'touch',
 535: 'wake',
 536: 'tree',
 537: 'morning',
 538: 'mine',
 539: 'ten',
 540: 'called',
 541: 'came',
 542: 'seek',
 543: 'weve',
 544: 'sense',
 545: 'getting',
 546: 'kiss',
 547: 'writing',
 548: 'needs',
 549: 'deserve',
 550: 'dance',
 551: 'front',
 552: 'greatest',
 553: 'memories',
 554: 'sky',
 555: 'joy',
 556: 'feet',
 557: 'used',
 558: 'nor',
 559: 'value',
 560: 'age',
 561: 'longer',
 562: 'wouldnt',
 563: 'certain',
 564: 'okay',
 565: 'spend',
 566: 'run',
 567: 'clary',
 568: 'arms',
 569: 'merely',
 570: 'hearts',
 571: 'blood',
 572: 'short',
 573: 'met',
 574: 'shes',
 575: 'miss',
 576: 'simply',
 577: 'thinks',
 578: 'intelligent',
 579: 'oh',
 580: 'wrote',
 581: 'brave',
 582: 'whom',
 583: 'written',
 584: 'can’t',
 585: 'cry',
 586: 'feelings',
 587: 'storm',
 588: 'anybody',
 589: 'poetry',
 590: 'wonder',
 591: 'powerful',
 592: 'magic',
 593: 'gave',
 594: 'guy',
 595: 'step',
 596: 'burn',
 597: 'moon',
 598: 'escape',
 599: 'passion',
 600: 'trees',
 601: 'pleasure',
 602: 'matters',
 603: 'fantasy',
 604: 'necessary',
 605: 'faith',
 606: 'late',
 607: 'leaves',
 608: 'drink',
 609: 'avoid',
 610: 'above',
 611: 'heard',
 612: 'along',
 613: 'travel',
 614: 'infinite',
 615: 'throw',
 616: 'library',
 617: 'questions',
 618: 'looks',
 619: 'usually',
 620: 'holding',
 621: 'youd',
 622: 'instead',
 623: 'poor',
 624: 'memory',
 625: 'hour',
 626: 'grief',
 627: 'meaning',
 628: 'becomes',
 629: 'hide',
 630: 'saw',
 631: 'weak',
 632: 'falling',
 633: 'sex',
 634: 'almost',
 635: 'play',
 636: 'shut',
 637: 'cool',
 638: 'genius',
 639: 'hot',
 640: 'deal',
 641: 'minute',
 642: 'places',
 643: 'dies',
 644: 'probably',
 645: 'coming',
 646: 'painful',
 647: 'skin',
 648: 'heaven',
 649: 'accept',
 650: 'you’ve',
 651: 'build',
 652: 'song',
 653: 'laughter',
 654: 'didn’t',
 655: 'bring',
 656: 'wind',
 657: 'remain',
 658: 'none',
 659: 'common',
 660: 'move',
 661: 'nature',
 662: 'purpose',
 663: 'money',
 664: 'waiting',
 665: 'except',
 666: 'air',
 667: 'kids',
 668: 'beyond',
 669: 'losing',
 670: 'middle',
 671: 'evil',
 672: 'tears',
 673: 'follow',
 674: 'running',
 675: 'went',
 676: 'sweet',
 677: 'bed',
 678: 'gods',
 679: 'they’re',
 680: 'لا',
 681: 'و',
 682: 'absolutely',
 683: 'fail',
 684: 'asleep',
 685: 'fairy',
 686: 'tales',
 687: 'large',
 688: 'angel',
 689: 'ready',
 690: 'tried',
 691: 'therefore',
 692: 'worst',
 693: 'mans',
 694: 'forward',
 695: 'wonderful',
 696: 'worry',
 697: 'that’s',
 698: 'present',
 699: 'forgotten',
 700: 'space',
 701: 'dying',
 702: 'whether',
 703: 'rain',
 704: 'amazing',
 705: 'road',
 706: 'count',
 707: 'kindness',
 708: 'eat',
 709: 'wasnt',
 710: 'white',
 711: 'reach',
 712: 'mouth',
 713: '“the',
 714: 'ways',
 715: '“i',
 716: 'judge',
 717: 'eye',
 718: 'sin',
 719: 'soon',
 720: 'spirit',
 721: 'across',
 722: 'lord',
 723: 'terrible',
 724: 'taken',
 725: 'silent',
 726: 'outside',
 727: 'greater',
 728: 'idea',
 729: 'humans',
 730: 'moving',
 731: 'hours',
 732: 'strange',
 733: 'education',
 734: 'sight',
 735: 'learning',
 736: 'sing',
 737: 'begins',
 738: 'fun',
 739: 'fighting',
 740: 'religion',
 741: 'form',
 742: 'paper',
 743: 'crying',
 744: 'piece',
 745: 'window',
 746: 'among',
 747: 'leaving',
 748: 'cut',
 749: 'toward',
 750: 'moments',
 751: 'songs',
 752: 'changing',
 753: 'madness',
 754: 'mess',
 755: 'enemies',
 756: 'needed',
 757: 'unhappy',
 758: 'chest',
 759: 'angry',
 760: 'problem',
 761: 'order',
 762: 'safe',
 763: 'troubles',
 764: 'trouble',
 765: 'whenever',
 766: 'someday',
 767: 'mistake',
 768: 'path',
 769: 'difficult',
 770: 'discover',
 771: 'share',
 772: 'blue',
 773: 'fell',
 774: 'please',
 775: 'interesting',
 776: 'figure',
 777: 'failure',
 778: 'hundred',
 779: 'wounds',
 780: 'given',
 781: 'fly',
 782: 'turned',
 783: 'pretend',
 784: 'telling',
 785: 'giving',
 786: 'stood',
 787: 'watch',
 788: 'glass',
 789: 'summer',
 790: 'hates',
 791: 'food',
 792: 'lips',
 793: 'protect',
 794: 'started',
 795: 'havent',
 796: 'ability',
 797: 'easier',
 798: 'ideas',
 799: 'rare',
 800: 'kissed',
 801: 'fill',
 802: 'opinion',
 803: 'instant',
 804: 'soft',
 805: 'depends',
 806: 'هو',
 807: 'sort',
 808: 'أن',
 809: 'changed',
 810: 'tea',
 811: 'anyway',
 812: 'baby',
 813: 'smiling',
 814: 'brain',
 815: 'opposite',
 816: 'indifference',
 817: 'problems',
 818: 'case',
 819: 'cup',
 820: 'attempt',
 821: 'doubt',
 822: 'ahead',
 823: 'flower',
 824: 'characters',
 825: 'rules',
 826: 'chance',
 827: 'boring',
 828: 'dragons',
 829: 'risk',
 830: 'gift',
 831: 'deeply',
 832: 'adventure',
 833: 'walls',
 834: 'guess',
 835: 'clothes',
 836: 'glory',
 837: 'taught',
 838: 'he’s',
 839: 'bird',
 840: 'fig',
 841: 'wear',
 842: 'destroy',
 843: 'actions',
 844: 'magnus',
 845: 'floor',
 846: 'hair',
 847: 'survive',
 848: 'fingers',
 849: 'force',
 850: 'ron',
 851: 'goodbye',
 852: 'rule',
 853: 'families',
 854: 'understanding',
 855: 'self',
 856: 'capable',
 857: 'fox',
 858: 'stuff',
 859: 'herself',
 860: 'burning',
 861: 'spring',
 862: 'naked',
 863: 'sorrow',
 864: 'doesn’t',
 865: 'country',
 866: 'wanting',
 867: 'talking',
 868: 'tells',
 869: 'من',
 870: 'chamber',
 871: 'choices',
 872: 'lifes',
 873: 'bravery',
 874: 'nonsense',
 875: 'lack',
 876: 'conscience',
 877: 'pride',
 878: 'reader',
 879: 'reads',
 880: 'lover',
 881: 'horrible',
 882: 'belief',
 883: 'fully',
 884: 'dumbledore',
 885: 'constantly',
 886: 'kept',
 887: 'allow',
 888: 'gold',
 889: 'car',
 890: 'cats',
 891: 'blind',
 892: 'bit',
 893: 'bigger',
 894: 'you’ll',
 895: 'sound',
 896: '2',
 897: 'deepest',
 898: 'warm',
 899: 'writer',
 900: 'greatness',
 901: 'science',
 902: 'character',
 903: 'believed',
 904: 'lucky',
 905: 'awful',
 906: 'job',
 907: 'sorry',
 908: 'hidden',
 909: 'cold',
 910: 'opinions',
 911: 'easily',
 912: 'somehow',
 913: 'complete',
 914: 'relationship',
 915: 'surprise',
 916: 'wed',
 917: 'dangerous',
 918: 'promise',
 919: 'precisely',
 920: 'realized',
 921: 'offer',
 922: 'create',
 923: 'empty',
 924: 'wild',
 925: 'sadness',
 926: 'lets',
 927: 'neither',
 928: 'hit',
 929: 'killed',
 930: 'peeta',
 931: 'i’ve',
 932: 'enemy',
 933: 'feels',
 934: 'tired',
 935: 'teacher',
 936: 'corner',
 937: 'flowers',
 938: 'missing',
 939: 'parents',
 940: 'return',
 941: 'comfort',
 942: 'suddenly',
 943: 'depression',
 944: 'eternal',
 945: 'نصف',
 946: 'created',
 947: '“it',
 948: 'theyll',
 949: 'explain',
 950: 'six',
 951: 'cause',
 952: 'admit',
 953: 'onto',
 954: 'sitting',
 955: 'happening',
 956: 'staring',
 957: 'opened',
 958: 'possibly',
 959: 'whose',
 960: 'answers',
 961: 'drive',
 962: 'differently',
 963: 'ignore',
 964: 'quiet',
 965: 'clear',
 966: 'brings',
 967: 'mate',
 968: 'yesterday',
 969: 'till',
 970: 'dogs',
 971: 'dust',
 972: 'fallen',
 973: 'lead',
 974: 'fit',
 975: 'transform',
 976: 'tessa',
 977: 'pretending',
 978: 'taking',
 979: 'date',
 980: 'list',
 981: 'she’s',
 982: 'pages',
 983: 'likes',
 984: 'understood',
 985: 'favorite',
 986: 'breath',
 987: 'pure',
 988: 'filled',
 989: 'scars',
 990: 'ordinary',
 991: 'grateful',
 992: 'literature',
 993: 'sees',
 994: 'advice',
 995: 'parts',
 996: 'simon',
 997: 'faster',
 998: 'fine',
 999: 'fate',
 1000: 'ugly',
 ...}

In [56]:
def predictor(model, tokenizer, text, max_len):
  text = text.lower()
  # Wrap text in a list so it tokenizes words instead of characters
  seq_list = tokenizer.texts_to_sequences([text])[0]
  # Pad the extracted 1D list of tokens
  padded_seq = pad_sequences([seq_list], maxlen=max_len, padding='pre')

  predict = model.predict(padded_seq, verbose=0)
  predict_index = np.argmax(predict)
  predicted_word = index_to_word[predict_index]

  return predicted_word

In [57]:
seed_word = "World is"
next_word = predictor(gru_model, tokenizer, seed_word, max_len)
print(next_word)

the

In [58]:
def generate_text(model, tokenizer, seed_text, max_len, n_words):
  for word in range(n_words):
    next_word = predictor(model, tokenizer, seed_text, max_len)
    if next_word == "":
      break
    seed_text += " " + next_word

  return seed_text

In [64]:
seed = "God is"
# Use a different variable name to avoid overwriting the function definition
generated_output = generate_text(gru_model, tokenizer, seed, max_len, 10)
print(generated_output)

God is a uniquely portable magic and forget what run many times

In [66]:
import pickle as pkl

In [68]:
with open("tokenizer.pkl", "wb") as file:
    pkl.dump(tokenizer, file)

In [69]:
with open("max_len.pkl", "wb") as file:
    pkl.dump(max_len, file)